"""Serves the pre-built reading catalogue.

The books are built once by scripts/build_catalog.py and committed, so nothing is fetched at
request time and the app works with no access to Wikisource. The index is small and is read
once; a whole book is read on demand, because the largest is a few hundred kilobytes and there
is no reason to hold every one of them in memory forever.
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path

CATALOG_DIRECTORY = Path(__file__).resolve().parents[1] / "data" / "catalog"
INDEX_FILE = CATALOG_DIRECTORY / "index.json"


@lru_cache(maxsize=1)
def load_index() -> list[dict]:
    if not INDEX_FILE.exists():
        return []
    return json.loads(INDEX_FILE.read_text(encoding="utf-8"))


def list_books(language_hint: str | None = None) -> list[dict]:
    books = load_index()
    if not language_hint:
        return books

    language = normalize_language(language_hint)
    return [book for book in books if book["language"] == language]


def normalize_language(language_hint: str) -> str:
    if language_hint.startswith("en"):
        return "en"
    if language_hint.startswith("ru"):
        return "ru"
    return "kk"


@lru_cache(maxsize=32)
def load_book(book_id: str) -> dict | None:
    # The id becomes a filename, so it must not be able to walk out of the catalogue directory.
    # Ids are generated by the build script, but this endpoint takes one from the network.
    if not book_id or not all(part.isalnum() or part == "-" for part in book_id):
        return None

    path = CATALOG_DIRECTORY / f"{book_id}.json"
    if not path.exists():
        return None
    return json.loads(path.read_text(encoding="utf-8"))
