// UI strings, ported verbatim from app/src/main/res/values*/strings.xml.
// %1$s / %1$d placeholders become {0}, {1}.
"use strict";

const STRINGS = {
  en: {
    app_name: "Sulu-Read",
    nav_reader: "Reader", nav_training: "Training", nav_progress: "Progress", nav_settings: "Settings",
    reader_letter_spacing: "Letter spacing", reader_line_height: "Line height", reader_ruler: "Reading ruler",
    reader_simplify_title: "In simple words", reader_simplify_loading: "Simplifying text...",
    reader_simplify_error: "Could not simplify the text. Try again.",
    reader_ai_help: "AI help", reader_ai_title: "AI help", reader_ai_loading: "Asking AI...",
    reader_ai_error: "AI help is temporarily unavailable. Please try again.", reader_close: "Close",
    loading_adaptation: "Sulu-Read is adapting the textbook text. Please wait...",
    processing_error_title: "Could not process the material",
    try_again: "Try again", ok: "OK", cancel: "Cancel",
    training_title: "Training",
    training_subtitle: "Short practice for sounds, syllables, word parts, and fluent reading.",
    training_source_ready: "Words from your text: {0}",
    training_source_empty: "Practice will use gentle starter words.",
    training_profile_loading: "Preparing profile...", training_loading: "Loading exercises...",
    training_intro_title: "6 focused tasks",
    training_intro: "The session moves from listening to syllables, decoding, and word parts. Work slowly and read each answer aloud.",
    training_start: "Start", training_start_practice: "Start practice",
    training_complete: "Good work! Let us give your eyes a short break.",
    training_complete_body: "Short repeated practice is more useful than rushing. Come back after a rest.",
    training_again: "Another 6 tasks", training_submit: "Check", training_next_word: "Next word",
    training_listen: "Listen", training_step_label: "Task {0} of {1}",
    training_skill_phonology: "Sounds", training_skill_decoding: "Decoding",
    training_skill_morphology: "Word parts", training_skill_visual: "Letter focus",
    training_goal_phonology: "Connect the sound of a word with how it looks on the page.",
    training_goal_decoding: "Choose the split that makes the word easier to read accurately.",
    training_goal_morphology: "Notice the base word and endings to support meaning.",
    training_goal_visual: "Check every letter and its order, not just the shape of the word.",
    training_instruction_auditory_match: "Listen first, then choose the printed word you heard.",
    training_instruction_morphology: "Choose the base and endings. This trains meaning, not memorization.",
    training_instruction_choice: "Choose the answer that matches the word.",
    training_instruction_word_recognition: "Listen, then choose the word that is written correctly.",
    training_feedback_correct: "Correct!", training_feedback_incorrect: "Not quite. Correct answer: {0}",
    training_feedback_correct_detail: "Read it once more smoothly before the next task.",
    training_feedback_incorrect_detail: "Look at the parts, then read the correct answer slowly.",
    training_feedback_saved_detail: "The answer is saved locally and will sync when possible.",
    training_sync_synced: "All answers synced", training_sync_pending: "Pending sync: {0}",
    progress_title: "Progress", progress_profile_loading: "Preparing profile...",
    progress_loading: "Loading progress...", progress_empty: "No data yet. Start a training session.",
    progress_total_exercises: "Exercises", progress_accuracy: "Accuracy",
    progress_average_response: "Average response", progress_current_difficulty: "Current difficulty",
    progress_phonological_skill: "Phonological skill", progress_decoding_skill: "Decoding fluency",
    progress_refresh: "Refresh",
    settings_title: "Settings", settings_language_title: "App language",
    settings_advanced: "Advanced", settings_hide_advanced: "Hide advanced",
    language_english: "English", language_russian: "Русский", language_kazakh: "Қазақша",
    account_title: "Account", account_username: "Username", account_password: "Password",
    account_display_name: "Display name", account_login: "Log in", account_register: "Create account",
    account_login_hint: "Use your username and password to continue.",
    account_register_hint: "Create a username and password for this student profile.",
    account_no_account: "No account?", account_has_account: "Already have an account?",
    account_register_link: "Register", account_login_link: "Log in",
    account_login_loading: "Signing in...", account_register_loading: "Creating account...",
    account_login_success: "Signed in successfully.", account_register_success: "Account created successfully.",
    account_login_error: "Sign-in failed. Check the username and password.",
    account_register_error: "Registration failed. Try another username or check the connection.",
    profile_student: "Student: {0}", profile_username: "Username: {0}",
    profile_user_id: "User ID: {0}", profile_selected_language: "Selected language: {0}",
    document_status_camera_ready: "Textbook page is ready. Sulu-Read is sending it for adaptation.",
    document_status_gallery_ready: "Textbook photo is loaded. Sulu-Read is sending it for adaptation.",
    photo_not_selected: "No photo was selected.",
    input_missing_link_or_scan: "Paste a link or scan a textbook page.",
    common_back: "Back",
    reader_adapted_text_title: "Adapted text", reader_back_home: "Home",
    reader_create_training_from_text: "Create training from this text",
    home_tagline: "See meaning, not just letters",
    home_support_message: "You can read calmly, at your own pace. Sulu-Read helps make text gentler for your eyes.",
    home_scan_textbook: "Scan textbook", home_scan_subtitle: "Take a photo or choose an existing image",
    document_status_source_camera: "Source: camera", document_status_source_gallery: "Source: media",
    document_status_no_photo: "No photo selected yet",
    document_sheet_title: "Add textbook photo",
    document_sheet_subtitle: "Photograph a page or upload an existing document image.",
    document_sheet_camera_title: "Photograph document",
    document_sheet_camera_subtitle: "The app will request camera access",
    document_sheet_gallery_title: "Upload from media",
    document_sheet_gallery_subtitle: "The app will request photo access",
    web_link_label: "Paste a link to an article or textbook", web_link_clear: "Clear link",
    adapt_loading_short: "Adapting...", adapt_text_button: "Adapt text",
    image_prepare_error: "Could not prepare the photo for upload.",
    api_empty_adapted_text: "The server returned empty adapted text.",
    api_adaptation_failed: "The server could not adapt the text.",
    api_adaptation_timeout: "Text adaptation took more than several minutes. Check the connection and try again.",
    api_connection_error: "Could not get a response from the Sulu-Read server. Check the internet and try again. First recognition on Hugging Face may take a few minutes.",
    error_profile_create: "Could not create the profile. Check the connection.",
    error_account_auth: "Could not sign in or register. Check the username, password, and connection.",
    error_training_load: "Could not load exercises. Try again.",
    error_progress_load: "Could not load progress.",
    training_attempt_save_error: "The answer was not saved. Try again.",
    focus_mode_title: "Focus reading", focus_mode_enter: "Read word by word",
    focus_mode_exit: "Back to the whole text",
    focus_listen: "Read the word aloud", focus_listen_start: "Listen", focus_listening: "Listening…",
    focus_help: "Show me",
    focus_mic_unavailable: "The microphone is not available, so this reading will not be checked.",
    focus_mic_permission: "Allow the microphone so the app can hear you read.",
    focus_check_off: "Read at your own pace — this reading is not checked.",
    focus_check_off_installed: "The installed app cannot hear the reading. Open the site in Safari if you want the reading checked.",
    focus_check_off_language: "iPhone cannot listen to reading in Kazakh, so this reading is not checked.",
    tts_silent: "This device is not playing the sound, so read the word yourself.",
    settings_theme_title: "Appearance", settings_theme_system: "Match the phone", settings_theme_light: "Light", settings_theme_dark: "Dark",
    focus_step_letters: "Letter by letter", focus_step_meaning: "What the word means",
    focus_pause_title: "Let's take a short break", focus_pause_continue: "I am ready",
    focus_progress: "Read without help: {0}%", focus_finished: "The text is finished.",
    focus_practise_words: "Practise the difficult words", focus_hint_dismiss: "Hide the hint",
    focus_next_word: "Next word", focus_check_now: "Stop and check",
    focus_tap_word_hint: "Tap any word to move the focus there.",
    focus_review_title: "Where the reading slipped",
    focus_review_clean: "Every word came out right.",
    focus_review_heard: "heard: {0}", focus_review_not_heard: "not heard",
    focus_review_nothing_heard: "Nothing was heard, so there is nothing to check.",
    document_sheet_file_title: "Book file",
    document_sheet_file_subtitle: "PDF, DOCX, EPUB, FB2 or TXT, split into pages",
    document_status_file_ready: "Book file ready", document_status_source_file: "File",
    file_not_selected: "No file was selected", file_prepare_error: "This file could not be opened",
    file_adaptation_failed: "This book could not be read",
    book_reader_title: "Book", book_page_of: "Page {0} of {1}",
    book_previous_page: "Back", book_next_page: "Next",
    book_page_from_scan: "This page was read from a scan, so a word may be wrong.",
    book_truncated_notice: "This book is long. The first {0} pages were opened.",
    word_picture_close: "Close", word_picture_credit: "Picture: {0} ({1}), Wikimedia",
    word_picture_unavailable: "The picture could not be loaded",
    catalog_title: "Library", catalog_subtitle: "Ready-made books, already prepared for reading",
    catalog_empty: "No books for this language yet", catalog_loading: "Opening the library…",
    catalog_book_meta: "Grade {0} · {1} pages",
    catalog_failed: "Could not reach the library. Check the connection.", catalog_retry: "Try again",
    tts_voice_missing: "This browser has no voice for this language, so reading aloud will sound wrong.",
    reader_listen: "Listen", reader_settings: "Reading settings"
  },
  ru: {
    app_name: "Sulu-Read",
    nav_reader: "Чтение", nav_training: "Тренировка", nav_progress: "Прогресс", nav_settings: "Настройки",
    reader_letter_spacing: "Расстояние между буквами", reader_line_height: "Высота строки",
    reader_ruler: "Линейка чтения",
    reader_simplify_title: "Простыми словами", reader_simplify_loading: "Упрощаем текст...",
    reader_simplify_error: "Не удалось упростить текст. Попробуйте ещё раз.",
    reader_ai_help: "AI-помощь", reader_ai_title: "AI-помощь", reader_ai_loading: "Спрашиваем AI...",
    reader_ai_error: "AI-помощь временно недоступна. Попробуйте ещё раз.", reader_close: "Закрыть",
    loading_adaptation: "Sulu-Read адаптирует текст учебника, пожалуйста подождите...",
    processing_error_title: "Не удалось обработать материал",
    try_again: "Попробовать снова", ok: "Понятно", cancel: "Отмена",
    training_title: "Тренировка",
    training_subtitle: "Короткая практика для звуков, слогов, частей слова и плавного чтения.",
    training_source_ready: "Слов из твоего текста: {0}",
    training_source_empty: "Тренировка возьмёт спокойные базовые слова.",
    training_profile_loading: "Профиль загружается...", training_loading: "Загружаем упражнения...",
    training_intro_title: "6 точных заданий",
    training_intro: "Сессия идёт от слуха к слогам, декодированию и частям слова. Работай спокойно и проговаривай ответы вслух.",
    training_start: "Начать", training_start_practice: "Начать практику",
    training_complete: "Хорошая работа! Давай сделаем короткий перерыв.",
    training_complete_body: "Короткая повторяемая практика полезнее спешки. Вернись после отдыха.",
    training_again: "Ещё 6 заданий", training_submit: "Проверить", training_next_word: "Следующее слово",
    training_listen: "Слушать", training_step_label: "Задание {0} из {1}",
    training_skill_phonology: "Звуки", training_skill_decoding: "Декодирование",
    training_skill_morphology: "Части слова", training_skill_visual: "Внимание",
    training_goal_phonology: "Свяжи звучание слова с тем, как оно выглядит на странице.",
    training_goal_decoding: "Выбери деление, которое помогает прочитать слово точно.",
    training_goal_morphology: "Заметь основу и окончания, чтобы лучше понимать смысл.",
    training_goal_visual: "Проверяй каждую букву и её место, а не только облик слова.",
    training_instruction_auditory_match: "Сначала послушай, потом выбери напечатанное слово.",
    training_instruction_morphology: "Выбери основу и окончания. Это тренирует понимание смысла.",
    training_instruction_choice: "Выбери ответ, который подходит к слову.",
    training_instruction_word_recognition: "Послушай слово и выбери то, что написано правильно.",
    training_feedback_correct: "Правильно!", training_feedback_incorrect: "Не совсем. Правильный ответ: {0}",
    training_feedback_correct_detail: "Прочитай это ещё раз плавно перед следующим заданием.",
    training_feedback_incorrect_detail: "Посмотри на части слова и медленно прочитай правильный ответ.",
    training_feedback_saved_detail: "Ответ сохранён на устройстве и отправится при подключении.",
    training_sync_synced: "Все ответы синхронизированы", training_sync_pending: "Ожидают синхронизации: {0}",
    progress_title: "Прогресс", progress_profile_loading: "Профиль загружается...",
    progress_loading: "Загружаем прогресс...", progress_empty: "Пока нет данных. Начните тренировку.",
    progress_total_exercises: "Упражнения", progress_accuracy: "Точность",
    progress_average_response: "Средний ответ", progress_current_difficulty: "Уровень сложности",
    progress_phonological_skill: "Фонологический навык", progress_decoding_skill: "Беглость чтения",
    progress_refresh: "Обновить",
    settings_title: "Настройки", settings_language_title: "Язык приложения",
    settings_advanced: "Дополнительно", settings_hide_advanced: "Скрыть дополнительно",
    language_english: "English", language_russian: "Русский", language_kazakh: "Қазақша",
    account_title: "Аккаунт", account_username: "Имя пользователя", account_password: "Пароль",
    account_display_name: "Имя на экране", account_login: "Войти", account_register: "Создать аккаунт",
    account_login_hint: "Введите логин и пароль, чтобы продолжить.",
    account_register_hint: "Создайте логин и пароль для профиля ученика.",
    account_no_account: "Нет аккаунта?", account_has_account: "Уже есть аккаунт?",
    account_register_link: "Зарегистрируйтесь", account_login_link: "Войдите",
    account_login_loading: "Выполняем вход...", account_register_loading: "Создаём аккаунт...",
    account_login_success: "Вход выполнен успешно.", account_register_success: "Аккаунт создан успешно.",
    account_login_error: "Войти не удалось. Проверьте логин и пароль.",
    account_register_error: "Регистрация не удалась. Попробуйте другой логин или проверьте подключение.",
    profile_student: "Ученик: {0}", profile_username: "Логин: {0}",
    profile_user_id: "ID пользователя: {0}", profile_selected_language: "Выбранный язык: {0}",
    document_status_camera_ready: "Страница учебника готова. Sulu-Read отправляет ее на обработку.",
    document_status_gallery_ready: "Фото учебника загружено. Sulu-Read отправляет его на обработку.",
    photo_not_selected: "Фото не выбрано.",
    input_missing_link_or_scan: "Вставьте ссылку или отсканируйте страницу учебника.",
    common_back: "Вернуться",
    reader_adapted_text_title: "Текст адаптирован", reader_back_home: "На главный",
    reader_create_training_from_text: "Создать тренировку из этого текста",
    home_tagline: "Видеть смысл, а не просто буквы",
    home_support_message: "Ты можешь читать спокойно, в своем темпе. Sulu-Read поможет сделать текст мягче для глаз.",
    home_scan_textbook: "Сканировать учебник", home_scan_subtitle: "Сделать фото или выбрать готовый снимок",
    document_status_source_camera: "Источник: камера", document_status_source_gallery: "Источник: медиа",
    document_status_no_photo: "Фото пока не выбрано",
    document_sheet_title: "Добавить фото учебника",
    document_sheet_subtitle: "Сфотографируйте страницу или загрузите готовый снимок документа.",
    document_sheet_camera_title: "Сфотографировать документ",
    document_sheet_camera_subtitle: "Приложение запросит доступ к камере",
    document_sheet_gallery_title: "Загрузить из медиа",
    document_sheet_gallery_subtitle: "Приложение запросит доступ к фото",
    web_link_label: "Вставьте ссылку на статью или учебник", web_link_clear: "Очистить ссылку",
    adapt_loading_short: "Адаптируем...", adapt_text_button: "Адаптировать текст",
    image_prepare_error: "Не удалось подготовить фото для отправки.",
    api_empty_adapted_text: "Сервер вернул пустой адаптированный текст.",
    api_adaptation_failed: "Сервер не смог адаптировать текст.",
    api_adaptation_timeout: "Адаптация текста заняла больше нескольких минут. Проверьте подключение и попробуйте снова.",
    api_connection_error: "Не удалось получить ответ от сервера Sulu-Read. Проверьте интернет и попробуйте еще раз. Первое распознавание на Hugging Face может занять несколько минут.",
    error_profile_create: "Не удалось создать профиль. Проверьте подключение.",
    error_account_auth: "Не удалось войти или зарегистрироваться. Проверьте логин, пароль и подключение.",
    error_training_load: "Не удалось загрузить упражнения. Попробуйте еще раз.",
    error_progress_load: "Не удалось загрузить прогресс.",
    training_attempt_save_error: "Ответ не был сохранен. Попробуйте еще раз.",
    focus_mode_title: "Чтение по словам", focus_mode_enter: "Читать по словам",
    focus_mode_exit: "Вернуться ко всему тексту",
    focus_listen: "Прочитай слово вслух", focus_listen_start: "Слушать", focus_listening: "Слушаю…",
    focus_help: "Подскажи",
    focus_mic_unavailable: "Микрофон недоступен, поэтому это чтение не проверяется.",
    focus_mic_permission: "Разреши микрофон, чтобы приложение слышало, как ты читаешь.",
    focus_check_off: "Читай в своем темпе — это чтение не проверяется.",
    focus_check_off_installed: "Установленное приложение не слышит чтение. Открой сайт в Safari, если нужна проверка.",
    focus_check_off_language: "iPhone не умеет слушать чтение на казахском, поэтому это чтение не проверяется.",
    tts_silent: "Это устройство не воспроизводит звук, поэтому прочитай слово сам.",
    settings_theme_title: "Оформление", settings_theme_system: "Как на телефоне", settings_theme_light: "Светлое", settings_theme_dark: "Темное",
    focus_step_letters: "По буквам", focus_step_meaning: "Что значит слово",
    focus_pause_title: "Сделаем небольшую паузу", focus_pause_continue: "Я готов",
    focus_progress: "Прочитано без подсказки: {0}%", focus_finished: "Текст закончился.",
    focus_practise_words: "Потренировать трудные слова", focus_hint_dismiss: "Скрыть подсказку",
    focus_next_word: "Следующее слово", focus_check_now: "Остановить и проверить",
    focus_tap_word_hint: "Нажми на любое слово, чтобы перейти к нему.",
    focus_review_title: "Где были ошибки",
    focus_review_clean: "Все слова прочитаны верно.",
    focus_review_heard: "услышано: {0}", focus_review_not_heard: "не услышано",
    focus_review_nothing_heard: "Ничего не услышано — проверять нечего.",
    document_sheet_file_title: "Файл книги",
    document_sheet_file_subtitle: "PDF, DOCX, EPUB, FB2 или TXT, поделим на страницы",
    document_status_file_ready: "Файл книги готов", document_status_source_file: "Файл",
    file_not_selected: "Файл не выбран", file_prepare_error: "Не удалось открыть этот файл",
    file_adaptation_failed: "Не удалось прочитать эту книгу",
    book_reader_title: "Книга", book_page_of: "Страница {0} из {1}",
    book_previous_page: "Назад", book_next_page: "Дальше",
    book_page_from_scan: "Эта страница распознана со скана, поэтому слово может быть неточным.",
    book_truncated_notice: "Книга длинная. Открыли первые {0} страниц.",
    word_picture_close: "Закрыть", word_picture_credit: "Картинка: {0} ({1}), Wikimedia",
    word_picture_unavailable: "Не удалось загрузить картинку",
    catalog_title: "Библиотека", catalog_subtitle: "Готовые книги, уже подготовленные для чтения",
    catalog_empty: "Для этого языка книг пока нет", catalog_loading: "Открываем библиотеку…",
    catalog_book_meta: "{0} класс · {1} стр.",
    catalog_failed: "Не удалось открыть библиотеку. Проверьте подключение.", catalog_retry: "Повторить",
    tts_voice_missing: "В этом браузере нет голоса для этого языка, поэтому чтение вслух будет звучать неправильно.",
    reader_listen: "Слушать", reader_settings: "Настройки чтения"
  },
  kk: {
    app_name: "Sulu-Read",
    nav_reader: "Оқу", nav_training: "Жаттығу", nav_progress: "Үлгерім", nav_settings: "Баптаулар",
    reader_letter_spacing: "Әріп аралығы", reader_line_height: "Жол биіктігі", reader_ruler: "Оқу сызғышы",
    reader_simplify_title: "Қарапайым сөзбен", reader_simplify_loading: "Мәтін жеңілдетілуде...",
    reader_simplify_error: "Мәтінді жеңілдету мүмкін болмады. Қайта көріңіз.",
    reader_ai_help: "AI көмегі", reader_ai_title: "AI көмегі", reader_ai_loading: "AI-дан сұрап жатырмыз...",
    reader_ai_error: "AI көмегі уақытша қолжетімсіз. Қайта көріңіз.", reader_close: "Жабу",
    loading_adaptation: "Sulu-Read оқулық мәтінін бейімдеп жатыр, сәл күтіңіз...",
    processing_error_title: "Материалды өңдеу мүмкін болмады",
    try_again: "Қайта көру", ok: "Түсінікті", cancel: "Бас тарту",
    training_title: "Жаттығу",
    training_subtitle: "Дыбыс, буын, сөз бөліктері және еркін оқу үшін қысқа жаттығу.",
    training_source_ready: "Мәтініңізден алынған сөздер: {0}",
    training_source_empty: "Жаттығу жеңіл бастапқы сөздерді қолданады.",
    training_profile_loading: "Профиль дайындалып жатыр...", training_loading: "Жаттығулар жүктелуде...",
    training_intro_title: "6 нақты тапсырма",
    training_intro: "Сессия тыңдаудан басталып, буынға, сөзді тануға және сөз бөліктеріне өтеді. Асықпай орындап, жауапты дауыстап оқыңыз.",
    training_start: "Бастау", training_start_practice: "Жаттығуды бастау",
    training_complete: "Жақсы жұмыс! Көзге демалыс берейік.",
    training_complete_body: "Қысқа әрі қайталанатын жаттығу асығудан пайдалырақ. Демалғаннан кейін қайта оралыңыз.",
    training_again: "Тағы 6 тапсырма", training_submit: "Тексеру", training_next_word: "Келесі сөз",
    training_listen: "Тыңдау", training_step_label: "Тапсырма {0} / {1}",
    training_skill_phonology: "Дыбыстар", training_skill_decoding: "Сөзді тану",
    training_skill_morphology: "Сөз бөліктері", training_skill_visual: "Зейін",
    training_goal_phonology: "Сөздің дыбысын оның жазылуымен байланыстырыңыз.",
    training_goal_decoding: "Сөзді дәл оқуға көмектесетін буынға бөлуді таңдаңыз.",
    training_goal_morphology: "Мағынаны жақсы түсіну үшін түбір мен жалғауларды байқаңыз.",
    training_goal_visual: "Сөздің жалпы бейнесіне емес, әр әріпке және оның орнына назар аударыңыз.",
    training_instruction_auditory_match: "Алдымен тыңдап, кейін естіген сөзді таңдаңыз.",
    training_instruction_morphology: "Түбір мен жалғауларды таңдаңыз. Бұл мағынаны түсінуге көмектеседі.",
    training_instruction_choice: "Сөзге сәйкес жауапты таңдаңыз.",
    training_instruction_word_recognition: "Сөзді тыңдап, дұрыс жазылған нұсқасын таңдаңыз.",
    training_feedback_correct: "Дұрыс!", training_feedback_incorrect: "Әлі дұрыс емес. Дұрыс жауап: {0}",
    training_feedback_correct_detail: "Келесі тапсырмаға дейін мұны тағы бір рет тұтас оқыңыз.",
    training_feedback_incorrect_detail: "Сөз бөліктеріне қарап, дұрыс жауапты баяу оқыңыз.",
    training_feedback_saved_detail: "Жауап құрылғыда сақталды және қосылым болғанда жіберіледі.",
    training_sync_synced: "Барлық жауап синхрондалды", training_sync_pending: "Синхрондау күтіп тұр: {0}",
    progress_title: "Үлгерім", progress_profile_loading: "Профиль дайындалып жатыр...",
    progress_loading: "Үлгерім жүктелуде...", progress_empty: "Әзірге дерек жоқ. Жаттығуды бастаңыз.",
    progress_total_exercises: "Жаттығулар", progress_accuracy: "Дәлдік",
    progress_average_response: "Орташа жауап", progress_current_difficulty: "Қиындық деңгейі",
    progress_phonological_skill: "Фонологиялық дағды", progress_decoding_skill: "Оқу еркіндігі",
    progress_refresh: "Жаңарту",
    settings_title: "Баптаулар", settings_language_title: "Қолданба тілі",
    settings_advanced: "Қосымша", settings_hide_advanced: "Қосымшаны жасыру",
    language_english: "English", language_russian: "Русский", language_kazakh: "Қазақша",
    account_title: "Аккаунт", account_username: "Пайдаланушы аты", account_password: "Құпия сөз",
    account_display_name: "Көрсетілетін ат", account_login: "Кіру", account_register: "Тіркелу",
    account_login_hint: "Жалғастыру үшін логин мен құпия сөзді енгізіңіз.",
    account_register_hint: "Оқушы профилі үшін логин мен құпия сөз жасаңыз.",
    account_no_account: "Аккаунт жоқ па?", account_has_account: "Аккаунтыңыз бар ма?",
    account_register_link: "Тіркеліңіз", account_login_link: "Кіріңіз",
    account_login_loading: "Кіріп жатырмыз...", account_register_loading: "Аккаунт жасалып жатыр...",
    account_login_success: "Кіру сәтті аяқталды.", account_register_success: "Аккаунт сәтті жасалды.",
    account_login_error: "Кіру мүмкін болмады. Логин мен құпия сөзді тексеріңіз.",
    account_register_error: "Тіркелу мүмкін болмады. Басқа логин қолданып көріңіз немесе қосылымды тексеріңіз.",
    profile_student: "Оқушы: {0}", profile_username: "Логин: {0}",
    profile_user_id: "Пайдаланушы ID: {0}", profile_selected_language: "Таңдалған тіл: {0}",
    document_status_camera_ready: "Оқулық беті дайын. Sulu-Read оны бейімдеуге жіберіп жатыр.",
    document_status_gallery_ready: "Оқулық фотосы жүктелді. Sulu-Read оны бейімдеуге жіберіп жатыр.",
    photo_not_selected: "Фото таңдалмады.",
    input_missing_link_or_scan: "Сілтемені енгізіңіз немесе оқулық бетін сканерлеңіз.",
    common_back: "Қайту",
    reader_adapted_text_title: "Мәтін бейімделді", reader_back_home: "Басты бет",
    reader_create_training_from_text: "Осы мәтіннен жаттығу жасау",
    home_tagline: "Тек әріп емес, мағынаны көру",
    home_support_message: "Өз қарқыныңмен, тыныш оқи аласың. Sulu-Read мәтінді көзге жеңілірек етеді.",
    home_scan_textbook: "Оқулықты сканерлеу", home_scan_subtitle: "Суретке түсіру немесе дайын фотоны таңдау",
    document_status_source_camera: "Дереккөз: камера", document_status_source_gallery: "Дереккөз: медиа",
    document_status_no_photo: "Фото әлі таңдалмады",
    document_sheet_title: "Оқулық фотосын қосу",
    document_sheet_subtitle: "Бетті суретке түсіріңіз немесе дайын құжат фотосын жүктеңіз.",
    document_sheet_camera_title: "Құжатты суретке түсіру",
    document_sheet_camera_subtitle: "Қолданба камераға рұқсат сұрайды",
    document_sheet_gallery_title: "Медиадан жүктеу",
    document_sheet_gallery_subtitle: "Қолданба фотоларға рұқсат сұрайды",
    web_link_label: "Мақала немесе оқулық сілтемесін енгізіңіз", web_link_clear: "Сілтемені тазалау",
    adapt_loading_short: "Бейімделуде...", adapt_text_button: "Мәтінді бейімдеу",
    image_prepare_error: "Фотоны жіберуге дайындау мүмкін болмады.",
    api_empty_adapted_text: "Сервер бос бейімделген мәтін қайтарды.",
    api_adaptation_failed: "Сервер мәтінді бейімдей алмады.",
    api_adaptation_timeout: "Мәтінді бейімдеу бірнеше минуттан ұзаққа созылды. Қосылымды тексеріп, қайта көріңіз.",
    api_connection_error: "Sulu-Read серверінен жауап алу мүмкін болмады. Интернетті тексеріп, қайта көріңіз. Hugging Face-та алғашқы тану бірнеше минутқа созылуы мүмкін.",
    error_profile_create: "Профиль жасау мүмкін болмады. Қосылымды тексеріңіз.",
    error_account_auth: "Кіру немесе тіркелу мүмкін болмады. Логинді, құпия сөзді және қосылымды тексеріңіз.",
    error_training_load: "Жаттығуларды жүктеу мүмкін болмады. Қайта көріңіз.",
    error_progress_load: "Үлгерімді жүктеу мүмкін болмады.",
    training_attempt_save_error: "Жауап сақталмады. Қайта көріңіз.",
    focus_mode_title: "Сөзбен оқу", focus_mode_enter: "Сөзбен оқу",
    focus_mode_exit: "Мәтіннің толық түріне қайту",
    focus_listen: "Сөзді дауыстап оқы", focus_listen_start: "Тыңдау", focus_listening: "Тыңдап тұрмын…",
    focus_help: "Көмектес",
    focus_mic_unavailable: "Микрофон қолжетімсіз, сондықтан бұл оқу тексерілмейді.",
    focus_mic_permission: "Оқығаныңды қолданба естуі үшін микрофонға рұқсат бер.",
    focus_check_off: "Өз қарқыныңмен оқы — бұл оқу тексерілмейді.",
    focus_check_off_installed: "Орнатылған қолданба оқуды естімейді. Тексеру қажет болса, сайтты Safari-де аш.",
    focus_check_off_language: "iPhone қазақша оқуды тыңдай алмайды, сондықтан бұл оқу тексерілмейді.",
    tts_silent: "Бұл құрылғы дыбысты ойнатпайды, сондықтан сөзді өзің оқы.",
    settings_theme_title: "Сыртқы түрі", settings_theme_system: "Телефондағыдай", settings_theme_light: "Ашық", settings_theme_dark: "Күңгірт",
    focus_step_letters: "Әріппен", focus_step_meaning: "Сөздің мағынасы",
    focus_pause_title: "Кішкене үзіліс жасайық", focus_pause_continue: "Дайынмын",
    focus_progress: "Көмексіз оқылды: {0}%", focus_finished: "Мәтін бітті.",
    focus_practise_words: "Қиын сөздерді жаттығу", focus_hint_dismiss: "Кеңесті жасыру",
    focus_next_word: "Келесі сөз", focus_check_now: "Тоқтатып тексеру",
    focus_tap_word_hint: "Кез келген сөзді бассаң, фокус соған көшеді.",
    focus_review_title: "Қай жерде қателестің",
    focus_review_clean: "Барлық сөз дұрыс оқылды.",
    focus_review_heard: "естілді: {0}", focus_review_not_heard: "естілмеді",
    focus_review_nothing_heard: "Ешнәрсе естілмеді, тексеретін ешнәрсе жоқ.",
    document_sheet_file_title: "Кітап файлы",
    document_sheet_file_subtitle: "PDF, DOCX, EPUB, FB2 немесе TXT, беттерге бөлеміз",
    document_status_file_ready: "Кітап файлы дайын", document_status_source_file: "Файл",
    file_not_selected: "Файл таңдалмады", file_prepare_error: "Бұл файлды ашу мүмкін болмады",
    file_adaptation_failed: "Бұл кітапты оқу мүмкін болмады",
    book_reader_title: "Кітап", book_page_of: "{1} беттің {0}-беті",
    book_previous_page: "Артқа", book_next_page: "Әрі қарай",
    book_page_from_scan: "Бұл бет скеннен оқылды, сондықтан сөз дәл болмауы мүмкін.",
    book_truncated_notice: "Кітап ұзын. Алғашқы {0} бет ашылды.",
    word_picture_close: "Жабу", word_picture_credit: "Сурет: {0} ({1}), Wikimedia",
    word_picture_unavailable: "Суретті жүктеу мүмкін болмады",
    catalog_title: "Кітапхана", catalog_subtitle: "Оқуға дайындалған кітаптар",
    catalog_empty: "Бұл тілде кітаптар әзірге жоқ", catalog_loading: "Кітапхана ашылуда…",
    catalog_book_meta: "{0} сынып · {1} бет",
    catalog_failed: "Кітапхананы ашу мүмкін болмады. Қосылымды тексеріңіз.", catalog_retry: "Қайталау",
    tts_voice_missing: "Бұл браузерде осы тілге арналған дауыс жоқ, сондықтан дауыстап оқу дұрыс естілмейді.",
    reader_listen: "Тыңдау", reader_settings: "Оқу параметрлері"
  }
};

// AppLanguage equivalent.
const APP_LANGUAGES = [
  { code: "en", backendHint: "en", defaultDisplayName: "Student", locale: "en-US", labelKey: "language_english" },
  { code: "ru", backendHint: "ru", defaultDisplayName: "Ученик", locale: "ru-RU", labelKey: "language_russian" },
  { code: "kk", backendHint: "kk", defaultDisplayName: "Оқушы", locale: "kk-KZ", labelKey: "language_kazakh" }
];

function langFromCode(code) {
  return APP_LANGUAGES.find((l) => l.code === code) || APP_LANGUAGES[2]; // Kazakh default
}
function normalizeLangCode(code) { return langFromCode(code).code; }
function backendHintFor(code) { return langFromCode(code).backendHint; }
function localeFor(code) { return langFromCode(code).locale; }
function defaultLangCode() {
  const system = (navigator.language || "kk").slice(0, 2);
  return APP_LANGUAGES.some((l) => l.code === system) ? system : "kk";
}

function t(key, ...args) {
  const lang = (window.APP_STATE && window.APP_STATE.languageCode) || "kk";
  let value = (STRINGS[lang] && STRINGS[lang][key]) || STRINGS.en[key] || key;
  args.forEach((arg, i) => { value = value.split(`{${i}}`).join(String(arg)); });
  return value;
}
